export const users = [
    {
      name: "John Doe",
      position: "Senior JavaScript Developer",
      office: "New York",
      age: 35,
      careerStart: "2007-09-01",
      salary: "$120,000",
    },
    {
      name: "Jane Smith",
      position: "Frontend Developer",
      office: "San Francisco",
      age: 30,
      careerStart: "2010-08-15",
      salary: "$115,000",
    },
    {
      name: "Michael Johnson",
      position: "Backend Developer",
      office: "Los Angeles",
      age: 40,
      careerStart: "2005-06-20",
      salary: "$130,000",
    },
    {
      name: "Emily Brown",
      position: "Full-Stack Developer",
      office: "Seattle",
      age: 28,
      careerStart: "2014-10-05",
      salary: "$105,000",
    },
    {
      name: "David Wilson",
      position: "DevOps Engineer",
      office: "Chicago",
      age: 38,
      careerStart: "2008-04-22",
      salary: "$125,000",
    },
    // {
    //   name: "Sarah Davis",
    //   position: "UI/UX Designer",
    //   office: "Austin",
    //   age: 32,
    //   careerStart: "2012-02-13",
    //   salary: "$95,000",
    // },
    // {
    //   name: "Chris Martinez",
    //   position: "Software Engineer",
    //   office: "Boston",
    //   age: 29,
    //   careerStart: "2015-11-09",
    //   salary: "$110,000",
    // },
    // {
    //   name: "Jessica Garcia",
    //   position: "Senior Frontend Developer",
    //   office: "San Diego",
    //   age: 34,
    //   careerStart: "2009-07-18",
    //   salary: "$118,000",
    // },
    // {
    //   name: "Brian Rodriguez",
    //   position: "Senior Backend Developer",
    //   office: "Houston",
    //   age: 37,
    //   careerStart: "2008-03-10",
    //   salary: "$122,000",
    // },
    // {
    //   name: "Ashley Lee",
    //   position: "Product Manager",
    //   office: "Denver",
    //   age: 33,
    //   careerStart: "2011-05-25",
    //   salary: "$135,000",
    // },
    // {
    //   name: "Kevin Harris",
    //   position: "Data Scientist",
    //   office: "New York",
    //   age: 31,
    //   careerStart: "2013-09-14",
    //   salary: "$125,000",
    // },
    // {
    //   name: "Laura Clark",
    //   position: "QA Engineer",
    //   office: "Miami",
    //   age: 27,
    //   careerStart: "2017-06-05",
    //   salary: "$100,000",
    // },
    // {
    //   name: "Daniel Young",
    //   position: "Cloud Architect",
    //   office: "Phoenix",
    //   age: 36,
    //   careerStart: "2009-01-20",
    //   salary: "$140,000",
    // },
    // {
    //   name: "Sophia Allen",
    //   position: "Machine Learning Engineer",
    //   office: "Dallas",
    //   age: 29,
    //   careerStart: "2015-12-03",
    //   salary: "$130,000",
    // },
    // {
    //   name: "James Hall",
    //   position: "Database Administrator",
    //   office: "San Francisco",
    //   age: 41,
    //   careerStart: "2003-03-11",
    //   salary: "$120,000",
    // },
    // {
    //   name: "Mia Adams",
    //   position: "Mobile Developer",
    //   office: "San Jose",
    //   age: 28,
    //   careerStart: "2016-08-21",
    //   salary: "$110,000",
    // },
    // {
    //   name: "Ethan Walker",
    //   position: "AI Specialist",
    //   office: "Portland",
    //   age: 34,
    //   careerStart: "2010-11-17",
    //   salary: "$135,000",
    // },
    // {
    //   name: "Olivia Scott",
    //   position: "Data Analyst",
    //   office: "Atlanta",
    //   age: 32,
    //   careerStart: "2012-06-30",
    //   salary: "$115,000",
    // },
    // {
    //   name: "William Moore",
    //   position: "System Administrator",
    //   office: "Charlotte",
    //   age: 39,
    //   careerStart: "2006-04-12",
    //   salary: "$105,000",
    // },
    // {
    //   name: "Isabella Thompson",
    //   position: "Network Engineer",
    //   office: "Washington D.C.",
    //   age: 33,
    //   careerStart: "2011-03-08",
    //   salary: "$110,000",
    // },
    // {
    //   name: "Matthew Robinson",
    //   position: "Security Engineer",
    //   office: "Las Vegas",
    //   age: 37,
    //   careerStart: "2008-09-27",
    //   salary: "$120,000",
    // },
    // {
    //   name: "Amelia White",
    //   position: "Technical Support Engineer",
    //   office: "Salt Lake City",
    //   age: 26,
    //   careerStart: "2018-02-19",
    //   salary: "$85,000",
    // },
    // {
    //   name: "Henry Lewis",
    //   position: "Software Architect",
    //   office: "Austin",
    //   age: 42,
    //   careerStart: "2002-07-23",
    //   salary: "$150,000",
    // },
    // {
    //   name: "Charlotte King",
    //   position: "Lead Developer",
    //   office: "Chicago",
    //   age: 35,
    //   careerStart: "2007-10-14",
    //   salary: "$135,000",
    // },
    // {
    //   name: "Liam Wright",
    //   position: "Frontend Engineer",
    //   office: "Seattle",
    //   age: 30,
    //   careerStart: "2011-12-01",
    //   salary: "$115,000",
    // },
    // {
    //   name: "Zoe Harris",
    //   position: "DevOps Manager",
    //   office: "San Francisco",
    //   age: 39,
    //   careerStart: "2005-05-30",
    //   salary: "$145,000",
    // },
    // {
    //   name: "Alexander Green",
    //   position: "Full-Stack Engineer",
    //   office: "Los Angeles",
    //   age: 31,
    //   careerStart: "2013-04-18",
    //   salary: "$120,000",
    // },
    // {
    //   name: "Ella Perez",
    //   position: "Web Developer",
    //   office: "Boston",
    //   age: 29,
    //   careerStart: "2015-01-10",
    //   salary: "$110,000",
    // },
    // {
    //   name: "Benjamin Mitchell",
    //   position: "Project Manager",
    //   office: "San Diego",
    //   age: 37,
    //   careerStart: "2008-07-25",
    //   salary: "$130,000",
    // },
    // {
    //   name: "Emily Rodriguez",
    //   position: "Data Engineer",
    //   office: "Denver",
    //   age: 32,
    //   careerStart: "2012-03-29",
    //   salary: "$125,000",
    // },
    // {
    //   name: "Jack Campbell",
    //   position: "iOS Developer",
    //   office: "New York",
    //   age: 34,
    //   careerStart: "2010-09-02",
    //   salary: "$115,000",
    // },
    // {
    //   name: "Lily Martinez",
    //   position: "Android Developer",
    //   office: "San Jose",
    //   age: 27,
    //   careerStart: "2017-05-04",
    //   salary: "$108,000",
    // },
    // {
    //   name: "Oliver Lopez",
    //   position: "Product Designer",
    //   office: "Miami",
    //   age: 33,
    //   careerStart: "2011-11-20",
    //   salary: "$112,000",
    // },
    // {
    //   name: "Ava Davis",
    //   position: "Graphic Designer",
    //   office: "Houston",
    //   age: 29,
    //   careerStart: "2015-06-15",
    //   salary: "$95,000",
    // },
    // {
    //   name: "Lucas Turner",
    //   position: "Solution Architect",
    //   office: "Austin",
    //   age: 41,
    //   careerStart: "2003-02-28",
    //   salary: "$140,000",
    // },
    // {
    //   name: "Charlotte Rivera",
    //   position: "Business Analyst",
    //   office: "Chicago",
    //   age: 36,
    //   careerStart: "2008-09-13",
    //   salary: "$120,000",
    // },
    // {
    //   name: "James Walker",
    //   position: "Network Administrator",
    //   office: "San Francisco",
    //   age: 38,
    //   careerStart: "2006-08-29",
    //   salary: "$110,000",
    // },
    // {
    //   name: "Mia Wright",
    //   position: "Cybersecurity Specialist",
    //   office: "New York",
    //   age: 35,
    //   careerStart: "2007-07-19",
    //   salary: "$125,000",
    // },
    // {
    //   name: "Henry Clark",
    //   position: "Tech Lead",
    //   office: "Seattle",
    //   age: 34,
    //   careerStart: "2010-01-22",
    //   salary: "$135,000",
    // }
]